//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeOnlineSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int IDCustomer { get; set; }
        public string fullnameCus { get; set; }
        public string phoneCus { get; set; }
        public string emailCus { get; set; }
        public Nullable<System.DateTime> DOBCus { get; set; }
        public string genderCus { get; set; }
        public string usernameCus { get; set; }
        public Nullable<int> statusCus { get; set; }
    }
}
