//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeOnlineSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int IDEmployee { get; set; }
        public string fullnameEmp { get; set; }
        public string phoneEmp { get; set; }
        public string emailEmp { get; set; }
        public Nullable<System.DateTime> DOBEmp { get; set; }
        public string genderEmp { get; set; }
        public string usernameEmp { get; set; }
        public string position { get; set; }
        public Nullable<int> statusEmp { get; set; }
    }
}
