//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeOnlineSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int IDPayment { get; set; }
        public Nullable<int> paymentType { get; set; }
    }
}
