//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeOnlineSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int IDProduct { get; set; }
        public Nullable<int> IDCategory { get; set; }
        public string nameProduct { get; set; }
        public Nullable<int> available { get; set; }
        public string imageUrl { get; set; }
        public Nullable<double> price { get; set; }
        public string description { get; set; }
        public byte[] photo { get; set; }
        public Nullable<int> status { get; set; }
    }
}
